apiVersion: v1
kind: Service
metadata:
  name: svelte-frontend-service
spec:
  selector:
    app: svelte-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30300
