name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_to_server:
    name: deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Docker Image
        working-directory: ./python_backend
        run: docker build . --tag jackdra90/fastapi_backend

      - name: Upload Backend Docker Image
        working-directory: ./python_backend
        run: docker image push jackdra90/fastapi_backend

      - name: Build Frontend Docker Image
        working-directory: ./sveltekit_frontend
        run: docker build . --tag jackdra90/svelte_frontend

      - name: Upload Frontend Docker Image
        working-directory: ./sveltekit_frontend
        run: docker image push jackdra90/svelte_frontend

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy All Services
        run: |
          sh kube_deploy_services.sh
